### PR TITLE
Feature/ia 5/challenge 2

### PR DESCRIPTION
**Pull request by MiguelAskar**
This screenshot shows the constants as requested by the exercise
Screen Shot 2021-07-28 at 2 46 48 PM

### CODE REVIEW

**Comment by MiguelAskar** [comment]
File UserInterfaceState.xcuserstate reamains in conflict because of an error in the ignore file when the repository was created. Camilo and I, both decided to continue with it for don't wasting time.

**Review by cmorales-globant — CHANGES_REQUESTED** [review]
The height of the rectangle is more than twice its width.

Check aspect ratio constraint.

**Comment by MiguelAskar** [comment]
> The height of the rectangle is more than twice its width.
> 
> Check aspect ratio constraint.

Aspect ratio fixed:

Screen Shot 2021-07-28 at 3 25 23 PM

**Review by cmorales-globant — APPROVED** [review]
Looks good after the fix 👍

**Comment by MiguelAskar** [comment]
> The height of the rectangle is more than twice its width.
> 
> Check aspect ratio constraint.

Aspect ratio fixed

**Pull request merged**
