### PR TITLE
Feature/ia 5/calculator challenge

### PR DESCRIPTION
**Pull request by MiguelAskar**
Calculator challenge is already finished, this screenshot shows the result:

Screen Shot 2021-07-31 at 5 40 06 PM

### CODE REVIEW

**Review by cmorales-globant — CHANGES_REQUESTED** [review]
Buttons are being rendered as rectangles rather than squares, also the label that would display numbers at the top of the UI has constraints that limits it's size too much so it is not able to display more than 1 number.

* Let's make sure all buttons are rendered with an 1:1 aspect ratio (squares)
* Let's make sure the result label uses the most of the available screen width.

Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-01 at 12 49 24

**Comment by MiguelAskar** [comment]
> Buttons are being rendered as rectangles rather than squares, also the label that would display numbers at the top of the UI has constraints that limits it's size too much so it is not able to display more than 1 number.
> 
> * Let's make sure all buttons are rendered with an 1:1 aspect ratio (squares)
> * Let's make sure the result label uses the most of the available screen width.
> 
> Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-01 at 12 49 24

Fixed:

Screen Shot 2021-08-02 at 12 08 26 PM

**Review by pablocalcagnino — CHANGES_REQUESTED** [review]
Ignore Safe areas

**Review by pablocalcagnino — CHANGES_REQUESTED** [review]
Ignore safe areas

**Comment by MiguelAskar** [comment]
> Ignore safe areas

Fixed: 
Screen Shot 2021-08-02 at 2 37 03 PM

**Review by pablocalcagnino — APPROVED** [review]

**Review by cmorales-globant — APPROVED** [review]

**Pull request merged**
